name: Flutter Workflow

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  flutter-test:
      strategy:
        matrix:
            os: [ubuntu-latest, macos-latest]
    
      runs-on: ${{ matrix.os }}

      defaults:
        run:
          working-directory: ./flutter_application_cards

      steps:
        - name: Checkout code
          uses: actions/checkout@v4.2.2
  
        - name: Get Flutter version
          id: flutter_version
          run: |
            FLUTTER_VERSION=$(flutter --version | head -n 1 | sed -E 's/Flutter ([0-9]+\.[0-9]+\.[0-9]+).*/\1/')
            echo "flutter-version=$FLUTTER_VERSION" >> $GITHUB_ENV
            echo "Flutter version: $FLUTTER_VERSION"
  
        - name: Set up Flutter
          uses: subosito/flutter-action@v2.18.0
          with:
            channel: stable
            flutter-version: ${{ env.flutter_version }}

        - name: Cache dependencies
          uses: actions/cache@v4.2.0
          with:
            path: |
              ~/.pub-cache
              .flutter-plugins
              .flutter-plugins-dependencies
            key: ${{ runner.os }}-flutter-${{ hashFiles('pubspec.yaml') }}
  
        - name: Install dependencies
          run: flutter pub get
  
        - name: Run Flutter analyze
          run: flutter analyze
  
        - name: Run tests
          run: flutter test
