name: Flutter Workflow

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  flutter-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get Flutter version
        id: flutter_version
        run: |
          FLUTTER_VERSION=$(flutter --version | head -n 1 | sed -E 's/Flutter ([0-9]+\.[0-9]+\.[0-9]+).*/\1/')
          echo "flutter-version=$FLUTTER_VERSION" >> $GITHUB_ENV
          echo "Flutter version: $FLUTTER_VERSION"

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: ${{ env.flutter_version }}

      - name: Install dependencies
        run: flutter pub get

      - name: Run Flutter analyze
        run: flutter analyze

      - name: Run tests
        run: flutter test
